<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>NINA.Plugin.SkyFlatCampaignManager</RootNamespace>
    <AssemblyName>SkyFlatCampaignManager</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <EnableDefaultPageItems>true</EnableDefaultPageItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NINA.Plugin" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyFlatCampaignManager.Core\SkyFlatCampaignManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
